services:
  db:
    image: mariadb:11.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    volumes:
      - ./database/mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_DATABASE: db_twitter
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8005:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

